import { Inter } from "next/font/google";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import "./twikoo.css";
import Banner from "@/components/banner";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Rightside from "@/components/rightside";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "葱苓sama",
  description: "a small blog station generated by next app.",
  icons: "/avatar1.avif",
  alternates: {
    canonical: "https://blog.ciraos.top",
    types: {
      "applicaiton/rss+xml": [{ url: "feed.xml", title: "RSS订阅" }],
    },
  },
};

export default function RootLayout({children,}:{children:React.ReactNode}) {
  return (
    <html lang="zh-CN">
      <body>
        <div id="CIRAOS">
          <NextTopLoader />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
