interface friendlink {
    groupName: string,
    groupDescr: string,
    child: string,
    name: string,
    link: string,
    avatar: string,
    descr: string,
    siteshot?: string,
    tag?: string,
    tagColor?: string,
}

export const friendlink = [

    {
        groupName: "框架",
        groupDescr: "框架相关站点",
        child: [
            { name: "React", link: "https://react.dev", avatar: "https://react.dev/favicon.ico", descr: "用于构建用户界面的JavaScript库" },
            { name: "Nextjs", link: "https://nextjs.org", avatar: "https://nextjs.org/favicon.ico", descr: "React应用开发框架" },
        ]
    },

    {
        groupName: "冰糖红茶",
        groupDescr: "一个神秘の组织",
        child: [
            { name: "小冰", link: "https://zfe.space", avatar: "https://zfe.space/images/headimage.png", descr: "做个有梦想的人！", tag: "小冰" },
            { name: "Akilarの糖果屋", link: "https://akilar.top", avatar: "https://npm.elemecdn.com/akilar-candyassets/image/siteicon/favicon.png", descr: "期待您的光临！" },
            { name: "张洪heo", link: "https://blog.zhheo.com", avatar: "https://npm.elemecdn.com/guli-heo/img/avatar2.png", descr: "分享设计与科技生活" },
            { name: "贰猹", link: "https://noionion.top", avatar: "https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg", descr: "用这生命中的每一秒，给自己一个不后悔的未来" },
        ],
    },

    {
        groupName: "大佬们",
        groupDescr: "dlddw~~~~~",
        child: [
            { name: "Lete乐特", link: "https://blog.imlete.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/lete.avif", descr: "人生只有一次，大胆的生活！！", siteshot: "https://webstack-siteshot.vercel.app/?link=blog.imlete.cn&viewport=1920x1080&fullPage=false&cache=7879680", tag: "乐特" },
            { name: "Android", link: "https://android99.com", avatar: "https://android99.com/img/avatar.png", descr: "边缘矩阵" },
            { name: "小康", link: "https://www.antmoe.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/xiaokang.avif", descr: "一个收藏回忆与分享技术的地方！" },
            { name: "Colsrch", link: "https://colsrch.cn", avatar: "https://bu.dusays.com/2022/02/23/cb173cbdcc7c6.png", descr: "愿多年以后，我可以酌一杯清酒，烂醉如泥，梦中回到我们的曾经。" },
            { name: "Black Flies", link: "https://www.yyyzyyyz.cn", avatar: "https://npm.elemecdn.com/imgscdn/img/202111191951780.JPG", descr: "When nothing goes right,just go left.", siteshot: "https://npm.elemecdn.com/imgscdn/img/202111191934973.jpg" },
            { name: "Tianli", link: "https://blog.tianli0.top", avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=507249007&spec=640", descr: "自知之明是最可贵的知识！" },
            { name: "Redish101", link: "https://blog.redish101.top", avatar: "https://avatars.githubusercontent.com/u/64068446?v=4", descr: "学生，人，活的。" },
            { name: "铭心石刻", link: "https://blog.kouseki.cn", avatar: "https://blog.kouseki.cn/imgs/avatar.webp", descr: "愿岁并谢，与友长兮" },
            { name: "纸鹿摸鱼处", link: "https://blog.zhilu.cyou", avatar: "https://www.zhilu.cyou/api/avatar.png", descr: "纸鹿至麓不知路，支炉制露不止漉" },
        ],
    },

    {
        groupName: "小伙伴们",
        groupDescr: "感谢陪伴~",
        child: [
            { name: "小N同学", link: "https://www.imcharon.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/nesxc.ico", descr: "青石落晚巷 故人未还乡" },
            { name: "轻笑Chuckle", link: "https://www.qcqx.cn", avatar: "https://www.qcqx.cn/img/head.webp", descr: "漫天倾尘,风中轻笑" },
            { name: "RootlexBlog", link: "https://blog.nalex.top", avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=1736191951&spec=640", descr: "寒蝉黎明之时，便是重生之日" },
            { name: "花裱", link: "https://dingzh.cc", avatar: "https://npm.elemecdn.com/ding-blogdemo@1.0.4/img/Favicon.png", descr: "为之则易，不为则难" },
            { name: "未央", link: "https://forever97.top", avatar: "https://forever97-picture-bed.oss-cn-hangzhou.aliyuncs.com/img/avatar.png", descr: "在人海里梦游" },
            { name: "低熵体", link: "https://blog.falling42.top", avatar: "https://npm.elemecdn.com/falling42-cdn@2.0.0/avatar.png", descr: "低熵体的博客-藏好自己，做好清理" },
            { name: "梦境学习站", link: "https://blog.godgy.xyz", avatar: "https://dreamwld.top/images/avatar.png", descr: "一个乐于免费分享的网站" },
            { name: "青桔气球", link: "https://blog.qjqq.cn/", avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640", descr: "分享网络安全与科技生活" },
            { name: "南雍随笔", link: "https://ydjsir.com.cn", avatar: "https://ydjsir.com.cn/img/avatar.png", descr: "守护我们最好的days~" },
            { name: "陈鑫磊", link: "https://blog.cxl2020mc.top", avatar: "https://public.img.cxl2020mc.top/avatar.png", descr: "这个人太懒了啥也没写......" },
            { name: "闪闪", link: "https://moechun.fun", avatar: "https://moechun.fun/img/avatar/hanajiang-2.png", descr: "来玩！玩累了…就睡觉！没问题的" },
            { name: "btwoa", link: "https://blog.btwoa.com", avatar: "https://blog.btwoa.com/author.avif", descr: "我仍相信人间滚烫" },
            { name: "Leonus", link: "https://blog.leonus.cn", avatar: "https://q1.qlogo.cn/g?b=qq&nk=553344777&s=5", descr: "进一寸有进一寸的欢喜。" },
            { name: "UyoAhz", link: "https://uyoahz.cn", avatar: "https://s1.ax1x.com/2022/11/27/zUFla6.png", descr: "集中精神，以气御剪" },
            { name: "Mycpen", link: "https://blog.cpen.top", avatar: "https://blog.cpen.top/img/avatar.jpg", descr: "这是一个有趣的博客" },
            { name: "淡忘", link: "https://lengmo714.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "莫忘少年凌云志，曾许人间第一流。" },
            { name: "冰火之砺", link: "https://blog.marice.top", avatar: "https://bu.dusays.com/2023/11/29/6567122d3f4a6.jpg", descr: "纵览人间烟火，品质坚如磐石" },
            { name: "Nuyoah", link: "https://262259.xyz", avatar: "https://q1.qlogo.cn/g?b=qq&nk=2496091142&s=640", descr: "以梦为马，不负韶华" },
            { name: "奇梦博客", link: "https://www.mryunqi.com", avatar: "https://q1.qlogo.cn/g?b=qq&nk=434658198&s=100", descr: "韶华不为少年留 恨悠悠 几时休" },
            { name: "Hercules", link: "https://blog.zhaoziyi.site", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/hercules.avif", descr: "数理化生一塌糊涂的理科生，对兴趣情有独钟的追寻！" },
            { name: "yiyun", link: "https://moeci.com", avatar: "https://moeci.com/images/avatar.png", descr: "The stupid one is me" },
            { name: "鹿啵包", link: "https://pochacco.top", avatar: "https://pochacco.top/img/Avatar.gif", descr: "落日橘子海，揽尽世间温柔" },
            { name: "LyShark", link: "https://www.lyshark.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/lyshark.avif", descr: "道，可道，非常道；名，可名，非常名。—— 老子《道德经》" },
            { name: "SinGO", link: "https://blog.xsnet.eu.org", avatar: "https://blog.xsnet.eu.org/images/avatar.jpg", descr: "害怕孤独，但又享受孤独" },
            { name: "xlenco", link: "https://blog.xlenco.top", avatar: "https://q1.qlogo.cn/g?b=qq&nk=1043865083&s=5", descr: "最好的地方,是没去过的地方。最好的时光，是回不来的时光。" },
            { name: "CoderToro", link: "https://codertoro.top", avatar: "https://bu.dusays.com/2023/01/17/63c67d92e2151.jpeg", descr: "一个懒人的博客。" },
            { name: "顾梦", link: "https://blog.gumengyo.top", avatar: "https://cloud.gumengyo.top/avatar.png", descr: "不想满心遗憾，那就全力以赴" },
            { name: "酷小呵", link: "https://www.kuhehe.top", avatar: "https://q1.qlogo.cn/g?b=qq&nk=3111349763&s=100", descr: "爱分享的酷小呵" },
            { name: "wskice", link: "https://wskice.cn", avatar: "https://wskice.cn/imgs/Rc-min.jpg", descr: "wskice的小破站" },
            { name: "Fgaoxing", link: "https://www.yt-blog.top", avatar: "https://npm.elemecdn.com/ytblogimg/webp/logo.webp", descr: "一个少年的博客" },
            { name: "小码同学", link: "https://blog.hikki.site", avatar: "https://bu.dusays.com/2022/11/04/636511250b21b.jpg", descr: "喜欢的东西就努力去追求，万一成功了呢!" },
            { name: "snailuu", link: "https://blogg.snailuu.cn", avatar: "https://oss.snailuu.cn/hexo/author/headphoto192-192.png", descr: "分享记录一切生活美好瞬间" },
            { name: "海底捞里没有鱼", link: "https://smileszh.cn", avatar: "https://bu.dusays.com/2023/06/10/648499e1299d0.jpg", descr: "平安喜乐，万事胜意" },
            { name: "rencai", link: "https://www.btrencai.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/rencai.avif", descr: "今天你学了么" },
            { name: "Plasmon222", link: "https://plasmon222.github.io", avatar: "https://bu.dusays.com/2023/05/12/645e45a3a55e1.jpg", descr: "一念既出，万山无阻" },
            { name: "神经蛙", link: "https://hexo.sjava.cn", avatar: "https://hexo.sjava.cn/img/pic.png", descr: "种一棵树最好的时间是十年前，其次是现在。" },
            { name: "阿豪", link: "https://ahao.ah.cn", avatar: "https://image.ahao.ah.cn/3cccc50598660ee1cece6e10be840f2.jpg", descr: "人间值得，未来可期" },
            { name: "牛魔博客", link: "https://www.nmwbk.com", avatar: "https://oss.nmwbk.com/wp-content/uploads/2020/10/20201010141735736.png", descr: "做一个有深度的博客" },
            { name: "屑殇", link: "https://jinghuashang.cn", avatar: "https://jinghuashang.cn/img/acc.jpg", descr: "一只咸鱼" },
            { name: "探人间", link: "https://www.hydsb0.com", avatar: "https://bu.dusays.com/2023/07/10/64abbf448d530.jpg", descr: "努力吃上更贵的雪糕！" },
            { name: "汐塔魔法屋", link: "https://blog.storical.space", avatar: "https://blog.storical.space/images/icon.png", descr: "种下一颗有故事的种子，让它带着魔法和奇迹生根发芽" },
            { name: "SuYi-宿仪", link: "https://www.thotz.top", avatar: "https://pic.imgdb.cn/item/6497c3401ddac507ccd9334c.jpg", descr: "随心写作，随缘阅读" },
            { name: "桜紺狸", link: "https://www.skira.top", avatar: "https://www.skira.top/img/lemonsuka.webp", descr: "一个闲聊萌新动漫技术交流站" },
            { name: "Marcus", link: "https://blog.marcus233.top", avatar: "https://img01.anheyu.com/useruploads/8/2023/08/09/64d307c2d8873.png", descr: "人间值得，未来可期" },
            { name: "yukliu", link: "https://yukliu.cn", avatar: "https://yukliu-1259463135.cos.ap-beijing.myqcloud.com/image/avatar.jpg", descr: "唯心所现,唯识所变" },
            { name: "ChenLi", link: "https://chenliss.cn", avatar: "https://bu.dusays.com/2023/08/17/64dcf6a805f44.png", descr: "记录生活,分享生活" },
            { name: "WilliamSun", link: "https://www.lowion.cn", avatar: "https://cdn.lowion.cn/img/hade.jpg", descr: "Code&&Life" },
            { name: "吮指原味姬", link: "https://www.yejinblok.cn/", avatar: "https://img01.anheyu.com/useruploads/243/2023/08/15/64db8a22b3b83.ico", descr: "无论什么时候，都不要后悔" },
            { name: "离子", link: "https://blog.loveak.top", avatar: "https://bu.dusays.com/2023/07/26/64c0758748106.ico", descr: "✨行则将至，做则必成✨" },
            { name: "hackcr", link: "https://blog.muzilix.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "路漫漫其修远兮，吾将上下而求索", tag: "hackcr" },
            { name: "偷闲小站", link: "https://blog.andypang.cc/", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/andypang.avif", descr: "跨越山海，终见曙光", tag: "Andy" },
            { name: "煮雪话河山", link: "https://blog.cent1pedee.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/cent1pede3.avif", descr: "如月之恒，如日之升。" },
            { name: "莫凌", link: "https://blog.mo0.top", avatar: "https://s1.ax1x.com/2023/09/05/pPsp5KP.jpg", descr: "无限可能，正在发生" },
            { name: "DragonJay", link: "https://dragonjay.top", avatar: "https://q.qlogo.cn/g?b=qq&nk=410714630&s=0", descr: "剑无眼，人有情，江湖路，步步惊。" },
            { name: "SerMs", link: "https://blog.serms.top", avatar: "https://bu.dusays.com/2023/10/11/65269ea6226c8.png", descr: "代码如诗，细节成就极致，逻辑成就完美。", "siteshot": "https://bu.dusays.com/2023/10/11/65264d86ddebb.png" },
            { name: "夜雨柠檬", link: "https://blog.yeyulemon.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "生于忧患，死于安乐。" },
            { name: "积跬", link: "https://www.jikui.cn", avatar: "https://www.jikui.cn/favicon.ico", descr: "不积跬步，无以至千里。", rss: "https://www.jikui.cn/feed/" },
            { name: "琅環书生", link: "https://www.zlog.us.kg", avatar: "https://z1.ax1x.com/2023/10/20/piFQxN8.jpg", descr: "无远弗届，皆有可能" },
            { name: "star", link: "https://blog.ahuaaa.cn", avatar: "https://q.qlogo.cn/headimg_dl?dst_uin=3156027735&spec=640&img_type=jpg", descr: "希望你可以在这里找到对你有用的知识" },
            { name: "墨尘", link: "https://mnchen.cn", avatar: "https://image.mnchen.cn/2023/12/mnochen.jpg", descr: "虽多尘色染，犹见墨痕浓", tag: "墨尘" },
            { name: "Chnci", link: "https://chnci.cc/", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/chnci.avif", descr: "一个普普通通的网站" },
            { name: "风起星辰", link: "https://blog.qiaoxiao.top/", avatar: "https://npm.elemecdn.com/yanblog-link@1.0.0/avatar.webp", descr: "行远自迩，登高自卑" },
            { name: "Mr.喵帕斯", link: "https://blog.mpsxx.top/", avatar: "https://blog.mpsxx.top/img/favicon.svg", descr: "熬夜伤身" },
            { name: "樱花小镇", link: "https://blog.sakura.vin", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "小园新种红樱树，闲绕花枝便当游。" },
            { name: "Qing", link: "https://blog.wuyuxi.cn", avatar: "https://cdnjson.com/images/2023/11/13/image254ba6fbd7eaeb6b.png", descr: "恰沐春风共同游，终只叹，木已舟。" },
            { name: "未知之旅", link: "https://blog.xenosp.cn", avatar: "https://cravatar.cn/avatar/4EA126708E5063621186D6B5895D2684", descr: "在未知中成长，超越自我" },
            { name: "HiPeach", link: "https://blog.opeach.cn", avatar: "https://npm.elemecdn.com/opicture@1.0.0/main/avatar.webp", descr: "妙不可言", tag: "Peach" },
            { name: "Calyee", link: "https://blog.calyee.top", avatar: "https://blog.calyee.top/img/avatar.jpg", descr: "追求充实，分享快乐" },
            { name: "小林笔记", link: "https://m.senlinm.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/xiaolinbiji.avif", descr: "轻生活，秒上签" },
            { name: "Mikuの次行星", link: "https://tkgso.fun", avatar: "https://cravatar.cn/avatar/ba76faef3cc8252bd0433b3515124389?s=512", descr: "心有多宽，世界就有多远" },
            { name: "Auriel", link: "https://www.auriel.top", avatar: "https://blog.auriel.top/img/avatar.png", descr: "生活的最佳状态，是在冷冷清清中风风火火" },
            { name: "Pzai", link: "https://blog.pzai.cloud", avatar: "https://blog.pzai.cloud/img/avatar.png", descr: "从入门到放弃" },
            { name: "小李同学", link: "https://blog.xxfer.cn", avatar: "https://blog.xxfer.cn/img/config/kpbl.jpg", descr: "一支努力变强的小彩笔" },
            { name: "Vincy云昔", link: "https://blog.vincy1230.net", avatar: "https://a.vincy1230.net/blogroll/avatar.jpg", descr: "太阳出来了，雾就会散的。" },
            { name: "御网尚书", link: "https://www.hack-gov.com.cn", avatar: "https://websitecssjs.oss-cn-beijing.aliyuncs.com/links/favicon.ico", descr: "愿以赤子之心，共建网络空间安全" },
            { name: "子染", link: "https://sbsb.life", avatar: "https://pic.imgdb.cn/item/637dbff316f2c2beb1d0d922.jpg", descr: "一直快乐" },
            { name: "大蛋糕", link: "https://lihaoyu.cn", avatar: "https://blog-api.lihaoyu.cn/images/profile/avatar-128x.webp", descr: "也许我们会分别，但我们将永远不会忘记彼此", tag: "大蛋糕" },
            { name: "星の野", link: "https://byer.top", avatar: "https://bu.dusays.com/2023/10/01/6519291503349.jpg", descr: "我自是年少，韶华倾负" },
            { name: "小杨日记", link: "https://anify.cn", avatar: "https://anify.cn/img/logo.jpg", descr: "及时当勉励，岁月不待人" },
            { name: "幻雪", link: "https://huanxueblog.top", avatar: "https://cdn.smartcis.cn/gh/huanxueshengmou/picture-host/huanxueblog_avatar.webp", descr: "腐烂于花海，致死于所爱" },
            { name: "九九九感冒绫", link: "https://miku-39.top", avatar: "https://pic1.imgdb.cn/item/6343babe16f2c2beb1acb692.jpg", descr: "这是我的梦想,我会慢慢的完成它" },
            { name: "羿潇贤鱼", link: "https://blog.raxianch.moe", avatar: "https://q1.qlogo.cn/g?b=qq&nk=1025212779&s=5", descr: "为之则易，不为则难。" },
            { name: "June", link: "https://blog.june-pj.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/june.avif", descr: "遇事不决，可问春风" },
            { name: "清羽飞扬", link: "https://blog.liushen.fun", avatar: "https://blog.liushen.fun/info/avatar.ico", descr: "柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜", tag: "六神花露水" },
            { name: "Cikaros", link: "https://blog.cikaros.top", avatar: "https://blog.cikaros.top/img/avatar.jpg", descr: "犹豫不决 才是最大的危害！" },
            { name: "梦爱吃鱼", link: "https://blog.bsgun.cn", avatar: "https://oss-cdn.bsgun.cn/logo/avatar.256.png", descr: "但愿日子清静抬头遇见的满是柔情" },
            { name: "浅小兮の梦", link: "https://zxwlove.xyz", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/qianxiaoxi.avif", descr: "从相遇的刹那开始就注定了别离！" },
            { name: "木瓜一块八", link: "https://www.lblssl.cn", avatar: "https://openls-img.lblssl.cn/avatar.jpg", descr: "记录了学习过程的点滴，定格美好生活瞬间" },
            { name: "云深处", link: "https://blog.likesrt.com", avatar: "https://blog.likesrt.com/upload/avatar.png", descr: "只在此山中，云深不知处" },
            { name: "Ariasaka", link: "https://blog.yaria.top", avatar: "https://weavatar.com/avatar/795ce413eb6c7485954b78283ffa3e00", descr: "人有悲欢离合 月有阴晴圆缺", "siteshot": "https://vercel.yaria.top/img/siteshot.png", tag: "Ariasaka" },
            { name: "梦想之都", link: "https://hexo.dreamerhe.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "朝着梦想前进" },
            { name: "可执行程序の天境小屋🥝", link: "https://blog.hanta2011.top/", avatar: "https://pic.imgdb.cn/item/65fe67989f345e8d03923ea6.jpg", descr: "The boy who lived", siteshot: "https://pic.imgdb.cn/item/66921dadd9c307b7e9da1e0e.png" },
            { name: "时空跃动", link: "https://stjhub.com", avatar: "https://cdn.stjhub.com/blog/avatar.jpg", descr: "无限可能，正在发生" },
            { name: "小妖客栈", link: "https://wangkay.top", avatar: "https://picture.wangkay.tech/zibill/2024/04/20240412165509269.png", descr: "wangkay knowledge base" },
            { name: "InsectMk", link: "https://insectmk.cn", avatar: "https://insectmk.cn/static/img/head/insectmk.jpg", descr: "每天都要微笑" },
            { name: "陆小启Kairo", link: "https://blog.luxq.space", avatar: "https://s21.ax1x.com/2025/02/23/pElRBdO.jpg", descr: "往者不谏，来者可追。" },
            { name: "PeterJXL", link: "https://www.peterjxl.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/peterJXL.avif", descr: "从 01 开始" },
            { name: "Ymkiux", link: "https://ymkiux.github.io", avatar: "https://ymkiux.github.io/img/avatar.jpeg", descr: "编程不易，易者不编" },
            { name: "Baili", link: "https://baili.tax", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/baili.avif", descr: "高山不语，静水流深；智者无言，心有日月。" },
            { name: "Elykia", link: "https://blog.elykia.cn", avatar: "https://bu.dusays.com/2024/10/25/671b2438203a6.gif", descr: "致以无暇之人", siteshot: "https://bu.dusays.com/2024/10/25/671b50dc2dd2b.png" },
            { name: "❖星港◎Star☆", link: "https://blog.starsharbor.com", avatar: "https://7.isyangs.cn/85/67b33ac68d72d-85.webp", descr: "以博客记录生活与热爱！" },
            { name: "lmz", link: "https://blog.imz.me", avatar: "https://pic.imgdb.cn/item/66cfd951d9c307b7e96dcfea.webp", descr: "仰望星空，脚踏实地。" },
            { name: "青稚", link: "https://blog.linux-qitong.top", avatar: "https://blog.linux-qitong.top/img/avatar.webp", descr: "越努力，越幸运." },
            { name: "寒烟志", link: "https://yanyuplus.cn", avatar: "https://yanyuplus.cn/favicon.svg", descr: "半山腰总是挤的，你得去山顶看看" },
            { name: "沐印小站", link: "https://c.undf.top", avatar: "https://img.undf.top/ob/1f51d3a166ab8fe93ca491fc80644de0.jpg", descr: "时间不在于你拥有多少，而在于你如何使用!" },
            { name: "小植", link: "https://blog.xiaoztx.top", avatar: "https://blog.xiaoztx.top/img/xiaozhi.jpg", descr: "生生不息，好运不止" },
            { name: "eastwind", link: "https://1wind.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/eastwind.avif", descr: "东风不与周郎便" },
            { name: "鹊楠", link: "https://blog.quenan.cn", avatar: "https://i.p-i.vip/43/20240913-66e403f2331ec.webp", descr: "世界那么大，我想去看看" },
            { name: "一粒微尘", link: "https://blog.667408.xyz", avatar: "https://blog.667408.xyz/favicon.ico", descr: "撷光以望，纳星于瞳" },
            { name: "p6oy", link: "https://p6oy.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "叼毛一个，啥也不会。" },
            { name: "朽丘秋雨", link: "https://koxiuqiu.cn", avatar: "https://cdn.koxiuqiu.cn/koxiuqiu/img/favicon.webp", descr: "一定会和喜欢的人在夏日夜晚牵手慢步" },
            { name: "弈鸣小筑", link: "https://blog.lwtools.site", avatar: "https://static.lwtools.site/static/img/favicon.ico", descr: "功不唐捐，玉汝于成" },
            { name: "XingJi", link: "https://love.xingji.fun", avatar: "https://i.p-i.vip/47/20240920-66ed7b168c38c.jpg", descr: "迄今所有人生都大写着失败，但不妨碍我继续向前✨", siteshot: "https://i.p-i.vip/47/20240920-66ed7b6730ca9.png" },
            { name: "钧言极客", link: "https://www.jinjun.top", avatar: "https://www.jinjun.top/img/avatar.jpg", descr: "记录生活、爱好学习、不爱折腾" },
            { name: "胜天半子", link: "https://blog.291055.xyz", avatar: "https://i1.wp.com/ruom.wuaze.com/i/2024/11/02/166823.webp", descr: "事已至此，先吃饭吧😋", siteshot: "https://i1.wp.com/ruom.wuaze.com/i/2024/11/08/350149.webp" },
            { name: "叶泯希", link: "https://blog.418121.xyz/", avatar: "https://blog.418121.xyz/images/avatar.webp", descr: "意义是自己赐予的" },
            { name: "Pinpe", link: "https://pinpe.top", avatar: "https://pinpe.top/head.jpg", descr: "一个属于自己的云朵。" },
            { name: "陵长镜", link: "https://r1n.top/", avatar: "https://r1n.top/avatar_nr.jpg", descr: "Everything collapses, but you rise." },
            { name: "Hinai", link: "https://blog.woo.moe", avatar: "https://data.woo.moe/img/ico/104491469_0_r.png", descr: "曇花一現" },
            { name: "花生莲子粥", link: "https://blog.hslzz.cn", avatar: "https://hslzz.cn/favicon.ico", descr: "与世无争，不染于泥。" },
            { name: "彬彬加冰", link: "https://blog.wzwzx.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/binbin-w8sl.avif", descr: "走进我的影子，触摸我的心" },
            { name: "虫不知喔", link: "https://blog.ssyc.moe", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/ssyc.avif", descr: "我要的正能量会发光！" },
            { name: "天翔TNXG", link: "https://tnxgmoe.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/tnxg.avif", descr: "明日尚未到来，希望凝于心上", tag: "TNXG" },
            { name: "Chinyuan Tai", link: "https://www.knlde.top", avatar: "https://cdn.jsdmirror.com/gh/Kindle-deep/picx-images-hosting@master/avatar.avif", descr: "LOVE&PEACE", tag: "Knlde" },
            { name: "小智", link: "https://blog.cuixinyu.com", avatar: "https://blog.cuixinyu.com/img/others/avatar.png", descr: "记录学习踩坑" },
            { name: "安小歪", link: "https://blog.anxy.top", avatar: "https://imgse.koxiuqiu.cc/imgse/u/19/2025/02/20/67b737d854192.webp", descr: "记住你！自己！" },
            { name: "阿呆", link: "https://adai.fun", avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=1432231192&spec=640", descr: "分享学习有趣的知识。", siteshot: "https://q2.qlogo.cn/headimg_dl?dst_uin=1432231192&spec=640" },
            { name: "FrWalker", link: "https://blog.frwalker.top", avatar: "https://fastly.jsdelivr.net/npm/frwalker-blog-static@0.0.0/img/avatar.png", descr: "佛系躺平,懒得毕业,向往自由✨", siteshot: "https://fastly.jsdelivr.net/npm/frwalker-blog-static@0.0.0/img/blog.frwalker.top.jpg" },
            { name: "洋洋", link: "https://yangy.co", avatar: "https://yangy.co/upload/logo.png", descr: "洋洋的小小Blog" },
            { name: "SCFC", link: "https://blog.scfc.top", avatar: "https://imgse.koxiuqiu.cc/imgse/u/3/2025/02/23/67ba8ec850e25.png", descr: "可惜…屠龙少年终成恶龙", siteshot: 'https://imgse.koxiuqiu.cc/imgse/u/3/2025/02/23/67ba909509369.png' },
            { name: "凌尘k", link: "https://b.icxk.cn", avatar: "https://cdn.jsdelivr.net/gh/lck68/imagehost/img/tx.webp", descr: "于高山之巅，方见大河奔涌；于群峰之上，更觉长风浩荡。" },
            { name: "岚天小窝", link: "https://blog.ltya.top", avatar: "https://gravatar.ltya.top/avatar/5af06b461740fb2bd7467b8561399703?s=500", descr: "一只鸽子住在这里~" },
            { name: "微霞", link: "https://yuuu.org", avatar: "https://cdn.yuuu.org/img/avatar.webp", descr: "水风清，晚霞明" },
            { name: "OnewBlog", link: "https://blog.onedabuliu.cn/", avatar: "https://img.onedabuliu.cn/file/1741045424366_logo.jpg", descr: "学习是进步的阶梯", siteshot: "https://img.onedabuliu.cn/file/Snipaste_2025-03-10_17-08-40.png" },
            { name: "南蛮子懋和", link: "https://www.dao.js.cn", avatar: "https://img.dao.js.cn/zb_users/upload/2021/10/202110151634246697912592.png-webp", descr: "李懋和，俗名李栋梁。书法、国画爱好者，互联网安全与前端建设者。" },
            { name: "皓子", link: "https://howiehz.top", avatar: "https://howiehz.top/upload/ico.ico", descr: "互联网是一片海洋，网站犹如一座座孤岛漂浮在其上，唯有超链接将它们联系起来。而此处恰好就是一座小岛，欢迎访问皓子的小站。" },
            { name: "Ganzhe", link: "https://ganzhe2028.github.io", avatar: "https://pic.imgdb.cn/item/64895d391ddac507cce97bc3.webpg", descr: "顺其自然，持之以恒" },
            { name: "拂晓不辍", link: "https://aowu.dog", avatar: "https://aowu.dog/touxiang.png", descr: "老是在幻想自己是主角..." },
            { name: "幻想の日常", link: "https://blog.someo.top", avatar: "https://blog.someo.top/data/img/tx.jpeg", descr: "心随幻想，梦行无疆" },
            { name: "笔搁纸鸯", link: "https://b.wihi.top", avatar: "https://b.wihi.top/img/avatar.png", descr: "记我所想，记录生活，随心而为，仅此而已" },
            { name: "水深火乐", link: "https://webly.fun/blog", avatar: "https://webly.fun/favicon.ico", descr: "志向和热爱是伟大行为的双翼" },
            { name: "莫言小筑", link: "https://www.myxz.top", avatar: "https://www.myxz.top/img/avatar.avif", descr: "随风飘起，如同浮云。" },
            { name: "小染笔记", link: "https://onoe.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "不必借光而行，你我皆是星辰." },
            // { name: "", link: "", avatar: "", descr: "" },
        ],
    },

    {
        groupName: "失联友链",
        groupDescr: "盼君归",
        child: [
            // { name: "Littleink24", link: "", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "分享有用的知识" },
            { name: "呆逼", link: "https://blog.keepdai.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "一个兴趣使然的博客" },
            { name: "极东魔术昼寝结社", link: "https://bilibilianime.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "NULL" },
            { name: "TwoPair", link: "https://twopair.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "Talk is cheap, show me the code" },
            { name: "小城故事", link: "https://www.xindong350.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "小城故事~" },
            { name: "Milank", link: "https://blog.milank.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "学而时习之，不亦悦乎" },
            { name: "Travele_", link: "https://www.travele.cc", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "笔记，生活琐碎" },
            { name: "Deemo", link: "https://deemo.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "庆幸遇见你" },
            { name: "月山", link: "https://www.yueshan.asia", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "一花一世界，一叶一追寻。" },
            { name: "忽然笔记", link: "https://blog.huran.xyz", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "长风破浪会有时，直挂云帆济沧海" },
            { name: "二次元", link: "https://cbbkk.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "生命不息，折腾不止" },
            { name: "HopeBlog", link: "http://8.140.32.159:400", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "I see your point." },
            { name: "star", link: "https://www.cnortles.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "科学是使人的精神变得勇敢的最好途径" },
            { name: "松易涅", link: "https://blog.songyinie.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "学习，思考，表达" },
            { name: "Gahotx", link: "https://blog.gahotx.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "Do not repeat yourself" },
            { name: "锦瑟的糖果屋", link: "https://www.ijinse.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "锦瑟无端五十弦，一弦一柱思华年" },
            { name: "白小屋", link: "https://www.kjyyds.xyz", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "一只不会IT的笨蛋" },
            { name: "DeCheng", link: "https://hexo.dc6.fun", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "已持续稳定运行数年载的小破站" },
            { name: "DeCheng", link: "https://cyolc932.github.io", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "已持续稳定运行数年载的小破站" },
            { name: "九思博客", link: "https://www.kokoo.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "唯有爱与梦想不可辜负" },
            { name: "三水", link: "https://www.sanshui.vip", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "三水个人导航" },
            { name: "WindBack", link: "https://wndbac.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "各自努力，山顶再见" },
            { name: "圣奇宝枣", link: "https://shengqibaozao.vercel.app", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "有朋自远方来，不亦乐乎，愿与你相识，得闲饮茶" },
            { name: "未来信息", link: "https://www.wlxxq.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "希望在未来还能遇见你博客的信息" },
            { name: "星溢栈", link: "https://blog.xez.cc", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "摸鱼&代码两不误" },
            { name: "一个简单的技术分享页", link: "https://www.ran-feiran.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "以身为棋，胜天半子" },
            { name: "小志IT知识库", link: "https://www.czfq99.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "一个专注于安全领域的全栈博客" },
            { name: "头发收集屋", link: "https://lenjon.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "欢迎来到我的秋秋空间~" },
            { name: "泠风寒声", link: "https://blog.lfhsheng.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "沉浸在Touch Fish的海洋中无法自拔" },
            { name: "Moby", link: "https://isfalse.pro", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "技术、备忘录、区块链以及日常问题解决，希望通过对技术的应用，能够为日常生活带来一些附加价值" },
            { name: "LinuxWin", link: "https://lw232.jsd.heqia.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "青，取之于蓝，而青于蓝" },
            { name: "一川·MOLIPRE·BLOG", link: "https://blog.molipre.com", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/friends/molipre.avif", descr: "读万卷书，行万里路" },
            { name: "小朊朋友圈", link: "https://www.xrpyq.com", descr: "隔牖风惊竹，开门雪满山！", avatar: "https://q.qlogo.cn/g?b=qq&nk=227389436&s=640" },
            { name: "Mx", link: "https://www.wwru.cn", avatar: "https://static.mx142.cn/img/logo.png", descr: "一个分享知识和快乐的地方！" },
            { name: "Shine", link: "https://blog.shineyu.cn", avatar: "https://s3.bmp.ovh/imgs/2022/11/23/129c19d56d22c637.png", descr: "Let's go! Target: The Vast Stars!", siteshot: "https://s3.bmp.ovh/imgs/2022/12/28/fe2452f7c4ff48ee.png" },
            { name: "别亦难", link: "https://lazyingman.com", avatar: "https://bu.dusays.com/2023/06/23/64959cf745a4d.png", descr: "准时不定期更新" },
            { name: "Yuexin", link: "https://wyxogo.top", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "Keep Walking." },
            { name: "Darian.Ming", link: "https://blog.darian-ming.cn", avatar: "https://cdn.smartcis.cn/gh/ciraos/ciraos-static@main/img/404_1.avif", descr: "镜花水月，不过尔尔，无悔过去，不问将来" },
            { name: "Joker2Yue", link: "https://blog.joker2yue.cn", avatar: "https://resource.joker2yue.cn/blog/images/avatar_joker.jpg", descr: "Joker Never Plays Jokes." },
            { name: "辉辉博客", link: "https://www.hui.vin", avatar: "https://www.hui.vin/img/logo.png", descr: "乘风破浪逐水流,一路晴空月参差" },
        ],
    },
];
